import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      {/* <div style={{
        border: "3px solid red",
        padding: '10px',
        background: 'gold'
      }}>

        <Link href="/">Home</Link>
        <Link href="/admin">Admin</Link>
      </div> */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
